_target_: src.logger.CometMLWriter
project_name: "ASVspoof"
workspace: null
run_name: "run03"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to CometML
id_length: 32 # length of the run_id
log_code: false
log_graph: false
auto_metric_logging: false
auto_param_logging: false
